In [122]:
# necessary libraries :-

# creating Data
import numpy as np

# create container for NN
from tensorflow.keras.models import Sequential
# create layers
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [123]:
def label_encoder(n):

    if (n%3 ==0) and (n%5 ==0):
        # FizzBuzz
        return [0, 0, 0, 1]
    elif n%3 == 0:
      # Fizz
        return [1, 0, 0, 0]
    elif n%5 == 0:
      # Buzz
        return [0, 1, 0, 0]
    else:
      # Other
        return [0, 0, 1, 0]



In [124]:
# Generate training data
X_train = np.array(range(1, 101))

# label data ( with encoding)
y_train = np.array([label_encoder(n) for n in X_train])

In [125]:
X_train

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [126]:
j=1
for i in y_train:
  print(j,i)
  j +=1

1 [0 0 1 0]
2 [0 0 1 0]
3 [1 0 0 0]
4 [0 0 1 0]
5 [0 1 0 0]
6 [1 0 0 0]
7 [0 0 1 0]
8 [0 0 1 0]
9 [1 0 0 0]
10 [0 1 0 0]
11 [0 0 1 0]
12 [1 0 0 0]
13 [0 0 1 0]
14 [0 0 1 0]
15 [0 0 0 1]
16 [0 0 1 0]
17 [0 0 1 0]
18 [1 0 0 0]
19 [0 0 1 0]
20 [0 1 0 0]
21 [1 0 0 0]
22 [0 0 1 0]
23 [0 0 1 0]
24 [1 0 0 0]
25 [0 1 0 0]
26 [0 0 1 0]
27 [1 0 0 0]
28 [0 0 1 0]
29 [0 0 1 0]
30 [0 0 0 1]
31 [0 0 1 0]
32 [0 0 1 0]
33 [1 0 0 0]
34 [0 0 1 0]
35 [0 1 0 0]
36 [1 0 0 0]
37 [0 0 1 0]
38 [0 0 1 0]
39 [1 0 0 0]
40 [0 1 0 0]
41 [0 0 1 0]
42 [1 0 0 0]
43 [0 0 1 0]
44 [0 0 1 0]
45 [0 0 0 1]
46 [0 0 1 0]
47 [0 0 1 0]
48 [1 0 0 0]
49 [0 0 1 0]
50 [0 1 0 0]
51 [1 0 0 0]
52 [0 0 1 0]
53 [0 0 1 0]
54 [1 0 0 0]
55 [0 1 0 0]
56 [0 0 1 0]
57 [1 0 0 0]
58 [0 0 1 0]
59 [0 0 1 0]
60 [0 0 0 1]
61 [0 0 1 0]
62 [0 0 1 0]
63 [1 0 0 0]
64 [0 0 1 0]
65 [0 1 0 0]
66 [1 0 0 0]
67 [0 0 1 0]
68 [0 0 1 0]
69 [1 0 0 0]
70 [0 1 0 0]
71 [0 0 1 0]
72 [1 0 0 0]
73 [0 0 1 0]
74 [0 0 1 0]
75 [0 0 0 1]
76 [0 0 1 0]
77 [0 0 1 0]
78 [1 0 

In [127]:
type(X_train)

numpy.ndarray

In [128]:
# Define the neural network model
model = Sequential()


model.add(Dense(32, input_shape=(1,), activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(4, activation='softmax'))

In [129]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [130]:
# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=0)

In [140]:
prediction = model.predict([3])
prediction

1/1 [==============================] - 0s 24ms/step


array([[0.24851517, 0.19476117, 0.41006196, 0.1466617 ]], dtype=float32)

In [141]:
y_pred= np.argmax(prediction)
y_pred

2

In [134]:
if y_pred == 3:
    print('FizzBuzz')
elif y_pred == 0:
    print('Fizz')
elif y_pred == 1:
    print('Buzz')
else:
    print(15)

15


In [135]:
print(y_train[15])

[0 0 1 0]


In [74]:
y_train[15]

array([0, 0, 1, 0])

In [85]:
y = np.array([0,0,1])
y


array([0, 0, 1])

In [101]:
y_train_one_hot = np.eye(4)[y_train]
y_train_one_hot

array([[[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]],

       [[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       ...,

       [[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]],

       [[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]]])